apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jp9ndqzv8-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jp9ndqzv8-java-quarkus-gitops